api_version = "2025-04"


[[extensions]]
uid = "6a21e0ac-4169-cd3e-0477-b56ec8f7f8ec1b33dd9b"
type = "ui_extension"
name = "order-status-thank-you"
handle = "order-status-thank-you"

  [extensions.settings]
    [[extensions.settings.fields]]
    key = "survey_title"
    type = "single_line_text_field"
    name = "Survey title"
    description = "Enter a title for the survey."

    [extensions.capabilities]
     api_access = true
     network_access = true

[[extensions.targeting]]
target = "purchase.thank-you.block.render"
module = "./src/Checkout.jsx"
export = "orderDetailsBlock"

